-- ═══════════════════════════════════════════════════════════════════════════
-- LM STAMPI — Script SQL per Supabase
-- Copia e incolla questo testo nell'SQL Editor di Supabase
-- (sezione "SQL Editor" nel menu a sinistra del tuo progetto)
-- ═══════════════════════════════════════════════════════════════════════════

-- ── TABELLA MATERIALI ────────────────────────────────────────────────────────
create table if not exists materiali (
  id          bigint generated by default as identity primary key,
  codice      text not null,
  nome        text not null,
  colore      text default 'Naturale',
  densita     numeric(6,3) not null default 1.0,
  tipo_essic  text default 'Nessuna',
  temp_essic  numeric(5,1) default 0,
  ore_essic   numeric(4,1) default 0,
  note        text default '',
  created_at  timestamptz default now()
);

-- ── TABELLA STAMPI ───────────────────────────────────────────────────────────
create table if not exists stampi (
  id                    bigint generated by default as identity primary key,
  codice                text not null,
  cliente               text default '',
  articolo              text default '',
  codice_articolo       text default '',
  pressa                text default '',
  temp_stampo           numeric(5,1) default 200,
  peso_stampata         numeric(8,2) default 0,
  densita               numeric(6,3) default 1.05,
  nr_cavita             integer default 1,
  tempo_ciclo           numeric(6,1) default 30,
  materiale_codice      text default '',
  master                text default '',
  concentrazione        numeric(5,2) default 0,
  tipo_essic            text default 'Nessuna',
  temp_essic            numeric(5,1) default 0,
  orario_essic          numeric(4,1) default 0,
  camera_calda          boolean default false,
  braccio_robot         boolean default false,
  recupero_materozza    boolean default false,
  presenza              boolean default false,
  tipo_scatola          text default '',
  pezzi_scatola         integer default 0,
  scatole_per_bancale   integer default 0,
  difetti_frequenti     text default '',
  note                  text default '',
  created_at            timestamptz default now()
);

-- ── SICUREZZA: accesso pubblico in lettura/scrittura (RLS disabilitato) ───────
-- Per un uso aziendale interno senza autenticazione utente, questa è
-- la configurazione più semplice. Se in futuro vuoi aggiungere login,
-- puoi abilitare RLS e aggiungere policy.
alter table materiali enable row level security;
alter table stampi    enable row level security;

-- Policy: chiunque abbia la anon key può leggere e scrivere
create policy "Accesso completo materiali" on materiali
  for all using (true) with check (true);

create policy "Accesso completo stampi" on stampi
  for all using (true) with check (true);
